--- 
document: 
  description: "Questo documento raccoglie le domande più frequenti e le procedure principali relative al servizio 18app. La documentazione originale può essere trovata all’indirizzo https://18app.italia.it."
  name: "Guida a 18app per gli esercenti"
  tags: 
    - 18app
